yagura/notifications/urls.py
from django.urls import path

from yagura.notifications.views import (
    EmailActivateView, EmailDeactivateCompleteView, EmailDeactivateView,
    EmailRecipientCreateView, EmailRecipientDeleteCompleteView,
    EmailRecipientDeleteView, EmailRecipientListView, SlackRecipientCreateView,
    SlackRecipientDeleteView, SlackRecipientListView
)

app_name = 'notifications'
urlpatterns = (
    path(
        'sites/<uuid:pk>/new',
        EmailRecipientCreateView.as_view(),
        name='add-recipient'),
    # Slack recipient urlconf
    path(
        'sites/<uuid:pk>/slack',
        SlackRecipientListView.as_view(),
        name='list-slack-recipient'),
    path(
        'sites/<uuid:pk>/slack/new',
        SlackRecipientCreateView.as_view(),
        name='add-slack-recipient'),
    path(
        'slack/<int:pk>/delete',
        SlackRecipientDeleteView.as_view(),
        name='delete-slack-recipient'),
    # Email recipient urlconf
    path(
        'sites/<uuid:pk>/email',
        EmailRecipientListView.as_view(),
        name='list-email-recipient'),
    path(
        'email/<int:pk>/delete',
        EmailRecipientDeleteView.as_view(),
        name='delete-email-recipient'),
    path(
        'delete/complete',
        EmailRecipientDeleteCompleteView.as_view(),
        name='delete-email-complete'),
    path(
        'emailactivate/<uuid:code>',
        EmailActivateView.as_view(),
        name='email-activate'),
    path(
        'emaildeactivate/<uuid:code>',
        EmailDeactivateView.as_view(),
        name='email-deactivate'),
    path(
        'emaildeactivate/complete',
        EmailDeactivateCompleteView.as_view(),
        name='email-deactivate-complete'),
)

yagura/project_template/myproj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

yagura/sites/urls.py
from django.urls import path

from yagura.sites.views import (
    SiteCreateView, SiteDeleteView, SiteDetailView, SiteDisableView,
    SiteEditTitleView, SiteListView
)

app_name = 'sites'
urlpatterns = [
    path('', SiteListView.as_view(), name='list'),
    path('new', SiteCreateView.as_view(), name='create'),
    path('<uuid:pk>', SiteDetailView.as_view(), name='detail'),
    path(
        '<uuid:pk>/edittitle',
        SiteEditTitleView.as_view(),
        name='edit-title'),
    path('<uuid:pk>/_disable', SiteDisableView.as_view(), name='disable'),
    path('<uuid:pk>/delete', SiteDeleteView.as_view(), name='delete'),
]

yagura/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

# Django Debug Toolbar(optional)
if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

yagura/notifications/models.py
from uuid import uuid4

from django.conf import settings
from django.db import models

from yagura.sites.models import Site


class EmailRecipient(models.Model):
    """Other email not users

    * Manage per recipient and target site
    """
    site = models.ForeignKey(
        Site, on_delete=models.CASCADE, related_name='recipients')
    email = models.EmailField()
    enabled = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = (
            ('site', 'email'),
        )

    def can_delete(self, user) -> bool:
        """Judge that ``user`` can delete this recipient.
        Each user can delete it

        * Creator of this recipient
        * Creator of this site

        :params user: Target user
        """
        if self.created_by == user:
            return True
        if self.site.created_by == user:
            return True
        return False


class EmailActivation(models.Model):
    """Email-recipient activation code
    """
    recipient = models.ForeignKey(EmailRecipient, on_delete=models.CASCADE)
    code = models.UUIDField()

    @classmethod
    def generate_code(cls, recipient):
        act = cls.objects.create(recipient=recipient, code=uuid4())
        return act


class EmailDeactivation(models.Model):
    """Email-recipient deactivation code
    """
    recipient = models.ForeignKey(EmailRecipient, on_delete=models.CASCADE)
    code = models.UUIDField()

    @classmethod
    def generate_code(cls, recipient):
        inst = cls.objects.create(recipient=recipient, code=uuid4())
        return inst


class SlackRecipient(models.Model):
    """Other notification recipient for Slack Incoming web-hook
    """
    site = models.ForeignKey(
        Site, on_delete=models.CASCADE, related_name='slack_recipients')
    url = models.URLField('Webhook URL')
    channel = models.CharField(
        'Channel name(optional)', max_length=22, null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = (
            ('site', 'url', 'channel'),
        )

    def can_delete(self, user) -> bool:
        """Judge that ``user`` can delete this recipient.
        Each user can delete it

        * Creator of this recipient
        * Creator of this site

        :params user: Target user
        """
        if self.created_by == user:
            return True
        if self.site.created_by == user:
            return True
        return False

yagura/notifications/forms.py
from django import forms
from django.forms import widgets

from yagura.notifications.models import EmailRecipient, SlackRecipient


class EmailRecipientCreateForm(forms.ModelForm):
    class Meta:
        model = EmailRecipient
        fields = ['site', 'email', ]
        widgets = {
            'site': widgets.HiddenInput(),
        }


class SlackRecipientCreateForm(forms.ModelForm):
    class Meta:
        model = SlackRecipient
        fields = ['site', 'url', 'channel', ]
        widgets = {
            'site': widgets.HiddenInput(),
        }


class SlackRecipientDeleteForm(forms.ModelForm):
    class Meta:
        model = SlackRecipient
        fields = ['id']

yagura/notifications/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, TemplateView
from django.views.generic.edit import FormMixin
from templated_email import send_templated_mail

from yagura.notifications.forms import (
    EmailRecipientCreateForm, SlackRecipientCreateForm,
    SlackRecipientDeleteForm
)
from yagura.notifications.models import (
    EmailActivation, EmailDeactivation, EmailRecipient, SlackRecipient
)
from yagura.sites.models import Site
from yagura.utils import get_base_url


# TODO: Set message
class EmailRecipientCreateView(LoginRequiredMixin, FormMixin, DetailView):
    model = Site
    form_class = EmailRecipientCreateForm
    template_name = 'notifications/emailrecipient_form.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['site'] = self.object
        return initial

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            recipient = form.instance
            recipient.created_by = request.user
            recipient.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        activation = EmailActivation.generate_code(form.instance)
        send_templated_mail(
            template_name='notifications/emailrecipient_confirm_activate',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[form.instance.email],
            context={
                'site': form.instance.site,
                'recipient': form.instance,
                'activation': activation,
                'base_url': get_base_url(),
            }
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'sites:detail', args=(self.object.id, ))


# TODO: Set message
class EmailRecipientDeleteView(LoginRequiredMixin, DetailView):
    model = EmailRecipient
    template_name = 'notifications/emailrecipient_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        recipient = self.get_object()
        if not recipient.can_delete(request.user):
            # TODO: Add error message
            return self.get(request, *args, **kwargs)
        deactivation = EmailDeactivation.generate_code(recipient)
        send_templated_mail(
            template_name='notifications/emailrecipient_confirm_delete',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[recipient.email],
            context={
                'site': recipient.site,
                'recipient': recipient,
                'deactivation': deactivation,
                'base_url': get_base_url(),
            }
        )
        # TODO: Redirect to site-detail
        return HttpResponseRedirect(
            reverse_lazy('notifications:delete-email-complete'))


# TODO: Not need, when redirect to site-detail
class EmailRecipientDeleteCompleteView(LoginRequiredMixin, TemplateView):
    template_name = 'notifications/emailrecipient_complete_delete.html'


class EmailRecipientListView(LoginRequiredMixin, ListView):
    model = EmailRecipient

    def get_queryset(self):
        qs_ = super().get_queryset()
        return qs_.filter(site_id=self.kwargs['pk'])

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['site'] = Site.objects.get(id=self.kwargs['pk'])
        return ctx


class EmailActivateView(DetailView):
    model = EmailActivation
    slug_field = 'code'
    slug_url_kwarg = 'code'

    def get_context_data(self, **kwargs):
        """If can get object, parent recipient enable.
        """
        ctx = super().get_context_data(**kwargs)
        # TODO: This proc is valid place?
        activation = self.get_object()
        activation.recipient.enabled = True
        activation.recipient.save()
        ctx['recipient'] = activation.recipient
        ctx['site'] = activation.recipient.site
        return ctx


# TODO: Set message?
class EmailDeactivateView(DetailView):
    model = EmailDeactivation
    slug_field = 'code'
    slug_url_kwarg = 'code'

    def get(self, request, *args, **kwargs):
        deactivation = self.get_object()
        deactivation.recipient.delete()
        # TODO: Set redirect for user state
        return HttpResponseRedirect(
            reverse_lazy('notifications:email-deactivate-complete'))


# TODO: Not need, if redirection for user state
class EmailDeactivateCompleteView(TemplateView):
    template_name = 'notifications/emaildeactivate_complete.html'


class SlackRecipientListView(LoginRequiredMixin, ListView):
    model = SlackRecipient

    def get_queryset(self):
        qs_ = super().get_queryset()
        return qs_.filter(site_id=self.kwargs['pk'])

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['site'] = Site.objects.get(id=self.kwargs['pk'])
        return ctx


# TODO: Set message
class SlackRecipientCreateView(LoginRequiredMixin, FormMixin, DetailView):
    model = Site
    form_class = SlackRecipientCreateForm
    template_name = 'notifications/slackrecipient_form.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['site'] = self.object
        return initial

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            recipient = form.instance
            recipient.created_by = request.user
            recipient.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'sites:detail', args=(self.object.id,))


class SlackRecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = SlackRecipient
    form_class = SlackRecipientDeleteForm

    def delete(self, request, *args, **kwargs):
        recipient = self.get_object()
        if not recipient.can_delete(request.user):
            return self.get(request, *args, **kwargs)
        resp = super().delete(request, *args, **kwargs)
        # TODO: Need transration
        messages.add_message(
            request, messages.INFO, f"Deleted slack-recipient")
        return resp

    def get_success_url(self):
        recipient = self.get_object()
        return reverse_lazy('sites:detail', args=(recipient.site.id, ))

yagura/notifications/templates/notifications/activation_detail.html
{% extends 'layouts/single_page.html' %}

{% block content_section %}
  <section class="jumbotron text-center">
    <div class="container">
      <h2 class="jumbotron-heading">Activation</h2>
    </div>
  </section>
{% endblock %}

{% block content_main %}
  <p>Thank you for activation.</p>
  <p>If {{ site.url }} state is changed, send notify for {{ recipient.email }}</p>
{% endblock %}

yagura/notifications/templates/notifications/deactivate_complete.html
{% extends 'layouts/single_page.html' %}

{% block content_section %}
  <section class="jumbotron text-center">
    <div class="container">
      <h2 class="jumbotron-heading">Deactivation</h2>
    </div>
  </section>
{% endblock %}

{% block content_main %}
  <p>Deactivation is completed.</p>
{% endblock %}

yagura/notifications/templates/notifications/emaildeactivate_complete.html
{% extends 'layouts/two_pane_single.html' %}
{# TODO: Need transration #}

{% block content_main %}
  <h1 class="title">Deactivation</h1>
  <div class="content">
    <p>
      Deactivation is completed.
    </p>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/emailrecipient_complete_delete.html
{% extends 'layouts/two_pane.html' %}
{# TODO: Need transration #}

{% block content_main %}
  <h1 class="title">Deleting notification</h1>
  <div class="content">
    <p>
      Sent a deactivate email.
    </p>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/emailrecipient_confirm_delete.html
{% extends 'layouts/two_pane.html' %}
{% load yagura_notifications %}

{% block content_main %}
  <h1 class="title">{% trans 'Confirm of deleteing recipient' %}</h1>
  <div class="content">
    <p>
      {% blocktrans with url=site.url %}Deleting notification for <strong>{{ recipient }}</strong>{% endblocktrans %}
    </p>
    {% can_delete emailrecipient request.user as can_delete_ %}
    {% if can_delete_ %}
    <form method="POST">
      {% csrf_token %}
      <button class="button is-danger" type="submit">{% trans 'Confirm' %}</button>
    </form>
    {% else %}
    <p>You do not have permission to delete this recipient</p>
    {% endif %}
  </div>
{% endblock %}

yagura/notifications/templates/notifications/emailrecipient_form.html
{% extends 'layouts/two_pane.html' %}
{% load bulma_tags %}
{% load url_filter %}
{# TODO: Need transration #}

{% block content_main %}
  <h1 class="title">Add new notification for {{ site.display_name|guard_basic_auth }}</h1>
  <div class="content">
    <form method="POST">
      {% csrf_token %}
      {{ form|bulma }}
      <div class="field">
        <button type="submit" class="button is-primary">{% trans 'Register' %}</button>
      </div>
    </form>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/emailrecipient_list.html
{% extends 'layouts/two_pane.html' %}
{% load yagura_notifications %}

{% block content_main %}
  <div class="level">
    <h1 class="title">{% trans 'List of notifications' %}</h1>
    <small><a href="{% url 'sites:detail' site.id %}">&lt;&lt; back to site detail</a></small>
    <a href="{% url 'notifications:add-recipient' site.id %}">
      Add notification
    </a>
  </div>
  <div class="content">
    <table>
      <tr>
        <td>
          {{ site.created_by.email }} <strong>(owner)</strong>
        </td>
        <td></td>
      </tr>
      {% for recipient in emailrecipient_list %}
      <tr>
        <td>
          {{ recipient.email }}
          {% if not recipient.enabled %}
            {# TODO: Need transration #}
            (not yet enabled)
          {% endif %}
        </td>
        <td>
          {% can_delete recipient request.user as can_delete_ %}
          {% if can_delete_ %}
            <a class="button is-danger is-small" href="{% url 'notifications:delete-email-recipient' recipient.id %}">
              Delete
            </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>

{% endblock %}

yagura/notifications/templates/notifications/recipient_complete_delete.html
{% extends 'layouts/two_pane.html' %}
{% load bootstrap4 %}

{% block content_main %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h2>Deleting notification</h2>
  </div>
  <div>
    <p>Sent a deactivate email.</p>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/recipient_confirm_delete.html
{% extends 'layouts/two_pane.html' %}
{% load bootstrap4 %}

{% block content_main %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h2>{% trans 'Confirm of deleteing recipient' %}</h2>
  </div>
  <div>
    <p>
      {% blocktrans with url=site.url %}Deleting notification for <strong>{{ recipient }}</strong>{% endblocktrans %}
    </p>
  </div>
  <div>
    <form method="POST">
      {% csrf_token %}
      {% trans 'Confirm' as confirm_label %}
      {% bootstrap_button confirm_label 'submit' %}
    </form>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/recipient_list.html
{% extends 'layouts/two_pane.html' %}
{% load bootstrap4 %}

{% block content_main %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h2>
      {% trans 'List of notifications' %}
      <small><a href="{% url 'sites:detail' site.id %}">&lt;&lt; back to site detail</a></small>
    </h2>
  </div>
  <div>
    <p>
      {% url 'notifications:add-recipient' site.id as url_to_add_notification %}
      {% bootstrap_button 'Add notification' 'link' href=url_to_add_notification size='xs' %}
    </p>
    <ul class="list-group">
      <li class="list-group-item">
        {{ site.created_by.email }} <strong>(owner)</strong>
      </li>
      {% for recipient in recipient_list %}
      <li class="list-group-item">
        {{ recipient.email }}
        {% if not recipient.enabled %}
        (not yet enabled)
        {% endif %}
        <div class="btn-group float-right">
          {% url 'notifications:delete-recipient' recipient.id as link_ %}
          {% bootstrap_button 'Delete' 'button' 'btn-danger' href=link_ size='xs' %}
        </div>
      </li>
      {% endfor %}
    <ul>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/slackrecipient_complete_delete.html
{% extends 'layouts/two_pane.html' %}
{# TODO: Need transration #}

{% block content_main %}
  <h1 class="title">Deleted notification</h1>
  <div class="content">
  </div>
{% endblock %}

yagura/notifications/templates/notifications/slackrecipient_confirm_delete.html
{% extends 'layouts/two_pane.html' %}
{% load yagura_notifications %}
{% load url_filter %}

{% block content_main %}
  <h1 class="title">{% trans 'Confirm of deleteing recipient' %}</h1>
  <div class="content">
    <p>
      {% blocktrans with name=slackrecipient.site.display_name|guard_basic_auth %}Deleting notification for <strong>{{ name }}</strong>{% endblocktrans %}
    </p>
    {% can_delete slackrecipient request.user as can_delete_ %}
    {% if can_delete_ %}
    <form method="POST">
      {% csrf_token %}
      <button class="button is-danger" type="submit">{% trans 'Confirm' %}</button>
    </form>
    {% else %}
    <p>You do not have permission to delete this recipient</p>
    {% endif %}
  </div>
{% endblock %}

yagura/notifications/templates/notifications/slackrecipient_form.html
{% extends 'layouts/two_pane.html' %}
{% load bulma_tags %}
{% load url_filter %}
{# TODO: Need transration #}

{% block content_main %}
  <h1 class="title">Add new notification recipient of Slack for {{ site.display_name|guard_basic_auth }}</h1>
  <div class="content">
    <form method="POST">
      {% csrf_token %}
      {{ form|bulma }}
      <div class="field">
        <button type="submit" class="button is-primary">{% trans 'Register' %}</button>
      </div>
    </form>
  </div>
{% endblock %}

yagura/notifications/templates/notifications/slackrecipient_list.html
{% extends 'layouts/two_pane.html' %}
{% load yagura_notifications %}
{# TODO: Need transration #}

{% block content_main %}
  <div class="level">
    <h1 class="title">{% trans 'List of Slack recipient' %}</h1>
    <small><a href="{% url 'sites:detail' site.id %}">&lt;&lt; back to site detail</a></small>
    <a href="{% url 'notifications:add-slack-recipient' site.id %}">
      Add notification
    </a>
  </div>
  <div class="content">
    <table>
      {% for recipient in slackrecipient_list %}
      <tr>
        <td>
          {{ recipient.url }}
        </td>
        <td>
          {% can_delete recipient request.user as can_delete_ %}
          {% if can_delete_ %}
            <a class="button is-danger is-small" href="{% url 'notifications:delete-slack-recipient' recipient.id %}">
              Delete
            </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}